### PR TITLE
SCLIENTS-197: set customer ID on carts

### PR DESCRIPTION
**Pull request by yanns**

### CODE REVIEW

**Comment by yanns** [comment]
@lauraluiz please review

**Comment by hajoeichler** [comment]
Do we have an integration test for customer changing actions?

**Comment by lauraluiz** [comment]
@hajoeichler I don't think we have. The closest thing is https://github.com/commercetools/sphere-play-sdk/blob/master/java-client/src/it/scala/CustomLineItemIntegrationSpec.scala
But we need for this use case at least. @yanns could you please create an IT for adding/removing the customer ID from the cart?

**Comment by yanns** [comment]
@lauraluiz IT: https://github.com/commercetools/sphere-play-sdk/commit/47487a5ffba428e4cdab75241ca5ff0faa880bd9

**Comment by lauraluiz** [comment]
Good, you can merge it! :+1:

**Pull request merged**
