### PR TITLE
add release note for SCLIENTS-197

### PR DESCRIPTION
**Pull request by yanns**
@lauraluiz please review

### CODE REVIEW

**Comment by lauraluiz** [comment]
@yanns good, release time :)

**Comment by schleichardt** [comment]
@lauraluiz @yanns I think you can change texts directly since they don't break the build.

**Comment by yanns** [comment]
@schleichardt thx for the info.
For my first change, I prefer a PR so that you have a chance to provide a feedback.
For the next changes, I'll try to update to release notes in the same PR as the change itself.

**Comment by butenkor** [comment]
Maybe you could provide release notes here too?
https://github.com/commercetools/sphere-play-sdk/releases

**Comment by yanns** [comment]
@butenkor done. Thx for pointing this!

**Comment by lauraluiz** [comment]
Thanks @butenkor, I forgot that, sorry!

**Pull request merged**
